/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Access Audit Events
         * @description Return a protected, credential-free page of security audit events.
         */
        get: operations["list_access_audit_events_api_v1_access_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Access Status
         * @description Bootstrap-friendly access check.
         *
         *     - Always returns 200 when protection is off, or when no key is sent
         *       (so the SPA can learn `enabled` without a 401 round-trip).
         *     - A valid HttpOnly session is preferred; the old header is accepted once
         *       to migrate clients from the localStorage-based implementation.
         */
        get: operations["get_access_status_api_v1_access_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Access Key */
        post: operations["verify_access_key_api_v1_access_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Accounts */
        get: operations["get_accounts_api_v1_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/sort-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Sort Order */
        put: operations["update_sort_order_api_v1_accounts_sort_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{wechat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_v1_accounts__wechat_id__get"];
        /** Update Account */
        put: operations["update_account_api_v1_accounts__wechat_id__put"];
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__wechat_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{wechat_id}/points_details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Points Details */
        get: operations["get_account_points_details_api_v1_accounts__wechat_id__points_details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{wechat_id}/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Program Points */
        delete: operations["delete_program_points_api_v1_accounts__wechat_id__programs__program_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Points Overview */
        get: operations["get_points_overview_api_v1_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Programs Api */
        get: operations["get_programs_api_api_v1_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Favorite Programs */
        get: operations["get_favorite_programs_api_v1_programs_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/unreported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unreported Programs */
        get: operations["get_unreported_programs_api_v1_programs_unreported_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Detail */
        get: operations["get_program_detail_api_v1_programs__program_id__get"];
        /** Update Program */
        put: operations["update_program_api_v1_programs__program_id__put"];
        post?: never;
        /** Delete Program */
        delete: operations["delete_program_api_v1_programs__program_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Ranking */
        get: operations["get_program_ranking_api_v1_programs__program_id__ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Rankings */
        get: operations["get_program_rankings_api_v1_programs__program_id__rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Stock */
        get: operations["get_program_stock_api_v1_programs__program_id__stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qinglong/crons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Qinglong Crons
         * @description Fetch all cron tasks from the QingLong panel (live, not DB mirror).
         */
        get: operations["list_qinglong_crons_api_v1_qinglong_crons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qinglong/crons/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Qinglong Cron Schedules
         * @description Batch update cron schedules on the QingLong panel, then resync mirror.
         */
        post: operations["update_qinglong_cron_schedules_api_v1_qinglong_crons_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qinglong/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Points */
        post: operations["report_points_api_v1_qinglong_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/bark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bark Settings */
        get: operations["get_bark_settings_api_v1_settings_bark_get"];
        put?: never;
        /** Update Bark Settings */
        post: operations["update_bark_settings_api_v1_settings_bark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/bark/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Bark Push */
        post: operations["test_bark_push_api_v1_settings_bark_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/database/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Database
         * @description Download a consistent snapshot of the SQLite database (backup).
         */
        get: operations["export_database_api_v1_settings_database_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/database/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Database
         * @description Restore database from an uploaded .db backup. Replaces current SQLite file.
         */
        post: operations["import_database_api_v1_settings_database_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Settings */
        get: operations["get_log_settings_api_v1_settings_logs_get"];
        put?: never;
        /** Update Log Settings */
        post: operations["update_log_settings_api_v1_settings_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/qinglong": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Qinglong Settings */
        get: operations["get_qinglong_settings_api_v1_settings_qinglong_get"];
        put?: never;
        /** Update Qinglong Settings */
        post: operations["update_qinglong_settings_api_v1_settings_qinglong_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/qinglong/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Qinglong Settings */
        post: operations["sync_qinglong_settings_api_v1_settings_qinglong_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Stock */
        post: operations["report_stock_api_v1_stock_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Center
         * @description Return a filtered page of stock items instead of the whole catalog.
         */
        get: operations["get_stock_center_api_v1_stock_center_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/hidden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hidden Products */
        get: operations["get_hidden_products_api_v1_stock_hidden_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/off-shelf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Off Shelf Products
         * @description 已下架（unlisted）商品 — 系统在处理 stock 上报时检测到老商品没出现在最新报告里，
         *     自动标记为 is_unlisted=1。和「已隐藏」（is_hidden，用户手动）完全独立。
         */
        get: operations["get_off_shelf_products_api_v1_stock_off_shelf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Or Update Product */
        post: operations["create_or_update_product_api_v1_stock_product_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/products/{product_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Hide Product */
        put: operations["hide_product_api_v1_stock_products__product_id__hide_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/products/{product_id}/relist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Relist Product
         * @description 把系统判定为「已下架」的商品手动恢复为活跃状态。和 /restore（取消手动隐藏）独立。
         */
        put: operations["relist_product_api_v1_stock_products__product_id__relist_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/products/{product_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Restore Product */
        put: operations["restore_product_api_v1_stock_products__product_id__restore_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Programs Stock Summary */
        get: operations["get_programs_stock_summary_api_v1_stock_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/programs/{program_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Products */
        get: operations["get_program_products_api_v1_stock_programs__program_id__products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Products Global */
        get: operations["search_products_global_api_v1_stock_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_v1_upload_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessAuditEventItem
         * @description Public, credential-free representation of one access audit event.
         */
        AccessAuditEventItem: {
            /** Client Id */
            client_id?: string | null;
            /** Event Time */
            event_time?: string | null;
            /** Event Type */
            event_type: string;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * AccessAuditEventPage
         * @description Paginated access audit response metadata and safe event items.
         */
        AccessAuditEventPage: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["AccessAuditEventItem"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** AccessVerifyRequest */
        AccessVerifyRequest: {
            /** Access Key */
            access_key: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Device */
            device?: string | null;
            /** Nickname */
            nickname?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** BarkSettingsUpdate */
        BarkSettingsUpdate: {
            /** Bark Device Key */
            bark_device_key?: string | null;
            /**
             * Bark Enabled
             * @default false
             */
            bark_enabled: boolean;
            /** Bark Push Time */
            bark_push_time?: string | null;
            /** Bark Server */
            bark_server?: string | null;
        };
        /** Body_import_database_api_v1_settings_database_import_post */
        Body_import_database_api_v1_settings_database_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_image_api_v1_upload_image_post */
        Body_upload_image_api_v1_upload_image_post: {
            /** File */
            file: string;
            /** Product Id */
            product_id?: string;
            /** Program Id */
            program_id?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogSettingsUpdate */
        LogSettingsUpdate: {
            /** Access Key */
            access_key?: string | null;
            /**
             * Access Protection Enabled
             * @default false
             */
            access_protection_enabled: boolean;
            /** Max Log Entries */
            max_log_entries: number;
            /** Max Retention Days */
            max_retention_days: number;
        };
        /** PaginatedProducts */
        PaginatedProducts: {
            /** Items */
            items: components["schemas"]["ProductResponse"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** PointsReportData */
        PointsReportData: {
            /** Wechat Accounts */
            wechat_accounts: components["schemas"]["WechatAccountData"][];
        };
        /** PointsReportRequest */
        PointsReportRequest: {
            data: components["schemas"]["PointsReportData"];
            /** Execution Time */
            execution_time?: string | null;
            /** Script Id */
            script_id: string;
        };
        /** ProductCreateUpdate */
        ProductCreateUpdate: {
            /**
             * Cash
             * @default 0
             */
            cash: number | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Points
             * @default 0
             */
            points: number;
            /** Product Id */
            product_id?: string | null;
            /** Product Name */
            product_name: string;
            /** Program Id */
            program_id: string;
            /**
             * Stock
             * @default 0
             */
            stock: number | null;
        };
        /** ProductData */
        ProductData: {
            /**
             * Cash
             * @default 0
             */
            cash: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Points
             * @default 0
             */
            points: number | null;
            /** Product Id */
            product_id?: string | null;
            /** Product Name */
            product_name: string;
            /**
             * Stock
             * @default 0
             */
            stock: number | null;
        };
        /** ProductResponse */
        ProductResponse: {
            /**
             * Cash
             * @default 0
             */
            cash: number | null;
            /** Hidden At */
            hidden_at?: string | null;
            /** Id */
            id: number;
            /** Image Local Path */
            image_local_path?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Is Hidden
             * @default 0
             */
            is_hidden: number | null;
            /**
             * Points
             * @default 0
             */
            points: number;
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Program Id */
            program_id: string;
            /**
             * Stock
             * @default 0
             */
            stock: number | null;
        };
        /** ProgramPointsData */
        ProgramPointsData: {
            /** Auth Type */
            auth_type?: string | null;
            /** Current Cash */
            current_cash?: number | null;
            /** Current Points */
            current_points?: number | null;
            /** Last Updated */
            last_updated?: string | null;
            /** Program Id */
            program_id: string;
            /** Program Name */
            program_name?: string | null;
        };
        /** ProgramStockSummary */
        ProgramStockSummary: {
            /** Product Count */
            product_count: number;
            /** Program Id */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Total Stock */
            total_stock: number;
        };
        /** ProgramUpdate */
        ProgramUpdate: {
            /** Auth Type */
            auth_type?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Is Favorite */
            is_favorite?: boolean | null;
            /** Is Pinned */
            is_pinned?: boolean | null;
            /** Note */
            note?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** QinglongCronBatchUpdate */
        QinglongCronBatchUpdate: {
            /** Items */
            items: components["schemas"]["QinglongCronScheduleUpdate"][];
        };
        /** QinglongCronScheduleUpdate */
        QinglongCronScheduleUpdate: {
            /** Id */
            id: unknown;
            /** Schedule */
            schedule: string;
        };
        /** QinglongSettingsUpdate */
        QinglongSettingsUpdate: {
            /** Ql Auto Sync Minutes */
            ql_auto_sync_minutes?: number | null;
            /** Ql Base Url */
            ql_base_url?: string | null;
            /** Ql Client Id */
            ql_client_id?: string | null;
            /** Ql Client Secret */
            ql_client_secret?: string | null;
            /** Ql Sync Mode */
            ql_sync_mode?: string | null;
        };
        /** SortOrderUpdate */
        SortOrderUpdate: {
            /** Wechat Ids */
            wechat_ids: string[];
        };
        /** StockReportRequest */
        StockReportRequest: {
            /** Expected Product Count */
            expected_product_count?: number | null;
            /** Products */
            products: components["schemas"]["ProductData"][];
            /** Program Id */
            program_id: string;
            /**
             * Snapshot Complete
             * @default true
             */
            snapshot_complete: boolean;
            /** Snapshot Id */
            snapshot_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WechatAccountData */
        WechatAccountData: {
            /** Nickname */
            nickname?: string | null;
            /** Phone */
            phone?: string | null;
            /** Points Data */
            points_data: components["schemas"]["ProgramPointsData"][];
            /** Wechat Id */
            wechat_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_access_audit_events_api_v1_access_audit_events_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                event_type?: string | null;
                client_id?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessAuditEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_access_status_api_v1_access_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_access_key_api_v1_access_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sort_order_api_v1_accounts_sort_order_put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SortOrderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_v1_accounts__wechat_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                wechat_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__wechat_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                wechat_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__wechat_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                wechat_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_points_details_api_v1_accounts__wechat_id__points_details_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                wechat_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_program_points_api_v1_accounts__wechat_id__programs__program_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                wechat_id: string;
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_summary_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_points_overview_api_v1_points_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_programs_api_api_v1_programs_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string | null;
                is_favorite?: boolean | null;
                tag?: string | null;
                status?: string | null;
                ql_status?: string | null;
                sort?: string | null;
                kind?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_favorite_programs_api_v1_programs_favorites_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unreported_programs_api_v1_programs_unreported_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_detail_api_v1_programs__program_id__get: {
        parameters: {
            query?: {
                sort?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_program_api_v1_programs__program_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_program_api_v1_programs__program_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_ranking_api_v1_programs__program_id__ranking_get: {
        parameters: {
            query?: {
                sort?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_rankings_api_v1_programs__program_id__rankings_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_stock_api_v1_programs__program_id__stock_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_qinglong_crons_api_v1_qinglong_crons_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_qinglong_cron_schedules_api_v1_qinglong_crons_schedules_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QinglongCronBatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_points_api_v1_qinglong_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointsReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bark_settings_api_v1_settings_bark_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bark_settings_api_v1_settings_bark_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarkSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_bark_push_api_v1_settings_bark_test_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_database_api_v1_settings_database_export_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_database_api_v1_settings_database_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_database_api_v1_settings_database_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_settings_api_v1_settings_logs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_log_settings_api_v1_settings_logs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qinglong_settings_api_v1_settings_qinglong_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_qinglong_settings_api_v1_settings_qinglong_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QinglongSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_qinglong_settings_api_v1_settings_qinglong_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_stock_api_v1_stock_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_center_api_v1_stock_center_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string | null;
                tag?: string | null;
                status?: string;
                price_mode?: string;
                cash_max?: number | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hidden_products_api_v1_stock_hidden_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_off_shelf_products_api_v1_stock_off_shelf_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_or_update_product_api_v1_stock_product_post: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_product_api_v1_stock_products__product_id__hide_put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                product_id: number;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relist_product_api_v1_stock_products__product_id__relist_put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                product_id: number;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_product_api_v1_stock_products__product_id__restore_put: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                product_id: number;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_programs_stock_summary_api_v1_stock_programs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramStockSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_products_api_v1_stock_programs__program_id__products_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string | null;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path: {
                program_id: string;
            };
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_products_global_api_v1_stock_search_get: {
        parameters: {
            query: {
                q: string;
                page?: number;
                size?: number;
            };
            header?: {
                "x-access-key"?: string | null;
            };
            path?: never;
            cookie?: {
                site_access_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_v1_upload_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_upload_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
