/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ProgramDetailDialog: typeof import('./components/ProgramDetailDialog.vue')['default']
    ProgramFilterBar: typeof import('./components/ProgramFilterBar.vue')['default']
    ProgramMetricStrip: typeof import('./components/ProgramMetricStrip.vue')['default']
    ProgramStockDialog: typeof import('./components/ProgramStockDialog.vue')['default']
    QinglongCronPlanDialog: typeof import('./components/QinglongCronPlanDialog.vue')['default']
    QinglongCronRow: typeof import('./components/QinglongCronRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsBarkSection: typeof import('./components/SettingsBarkSection.vue')['default']
    SettingsDatabaseSection: typeof import('./components/SettingsDatabaseSection.vue')['default']
    SettingsGeneralSection: typeof import('./components/SettingsGeneralSection.vue')['default']
    SettingsQinglongSection: typeof import('./components/SettingsQinglongSection.vue')['default']
    SettingsSectionNav: typeof import('./components/SettingsSectionNav.vue')['default']
    StockProductCard: typeof import('./components/StockProductCard.vue')['default']
    UserDesktopTable: typeof import('./components/UserDesktopTable.vue')['default']
    UserEditDialog: typeof import('./components/UserEditDialog.vue')['default']
    UserMobileCard: typeof import('./components/UserMobileCard.vue')['default']
    UserPointsDialog: typeof import('./components/UserPointsDialog.vue')['default']
  }
}
